### ISSUE TITLE
NotImplementedError:

### ISSUE THREAD

**Issue by Riviss** [bkontou/pick-view#1]
Running on file, encountered error: NotImplementedError: Trace with masked values found. This is not supported for this operation. Try the split() method on Trace/Stream to produce a Stream with unmasked Traces. Probably in the Stream module?

Also, suggest implementing a "Resume" option if the output file exists. Resume should go to the last (by index) status value that is not "unassigned"

**Comment by bkontou** [comment]
Some streams have no data and are masked, which can't be read or plotted. I added a bit from S-SNAP that should fix that. It just puts zeros where theres no data.

I think I'll add a file that records where you are after closing the gui that you can load everything from. Hopefully I can get it working so it will save in case of a crash.
